---1---
SELECT t.tt_id, t.TT_NAME, COUNT(DISTINCT e.ED_STUDENT) as students_count 
FROM TUTORS t LEFT JOIN  EDUCATION e ON t.TT_ID=e.ED_TUTOR 
GROUP BY t.tt_name, t.TT_ID;

---2---
SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME, COUNT (DISTINCT EDUCATION.ED_TUTOR) as tutors_count 
FROM STUDENTS JOIN EDUCATION ON STUDENTS.ST_ID=EDUCATION.ED_STUDENT 
GROUP BY STUDENTS.ST_NAME, STUDENTS.ST_ID ORDER BY STUDENTS.ST_ID ASC;