---1---
SELECT tutors.tt_id, TUTORS.TT_NAME, COUNT(DISTINCT EDUCATION.ED_STUDENT) as students_count 
FROM TUTORS LEFT JOIN  EDUCATION ON tutors.TT_ID=education.ED_TUTOR 
GROUP BY tutors.tt_name, TUTORS.TT_ID;

---2---
SELECT STUDENTS.ST_ID, STUDENTS.ST_NAME, COUNT (DISTINCT EDUCATION.ED_TUTOR) as tutors_count 
FROM STUDENTS JOIN EDUCATION ON STUDENTS.ST_ID=EDUCATION.ED_STUDENT 
GROUP BY STUDENTS.ST_NAME, STUDENTS.ST_ID ORDER BY STUDENTS.ST_ID ASC;